spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
        filter:
          enabled: true
  application:
    name: UserService
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true




